### ISSUE TITLE
怎样对不同的文件设置不同的data参数？

### ISSUE THREAD

**Issue by blankyao** [aralejs/upload#10]
我看data参数只在初始化时赋一次值，那如果我想为每个文件都传不同的data（比如文件的sequence id）该怎样做呢？

**Comment by lepture** [comment]
@blankyao 应该是不支持。不知道你期望的 API 长什么样子？

**Comment by blankyao** [comment]
@lepture 想到一个不太好的办法，可以将data参数暴露出来，这样就可以在外部通过upload.data来修改，比如通过change回调来修改。

**Comment by lizzie** [comment]
不知道后来有没替代方法, 目前的 uploader 不支持对不同文件设置不同 data 参数. 能否 data 按格式约定下?
