### ISSUE TITLE
无法隐藏

### ISSUE THREAD

**Issue by blacksunset** [aralejs/upload#21]
1.这个form能不能不基于body来决定定位，或者给ID也可以！有时候不需要显示的时候，想把它隐藏。现在的问题是，一直占用了一个位置在那里，点中的话就会打开上传框。

2.看到跟新日志说可以选择同一个文件，但是我试过，当连续选择同一个文件还是无法上传！

**Comment by lizzie** [comment]
目前代码里写死插入到 body 中的. 欢迎 pull request!

**Comment by blacksunset** [comment]
再成功或者失败的回调函数里面手动调用下：this.refreshInput();

**Comment by lizzie** [comment]
见 https://github.com/aralejs/upload/pull/25 添加了 enable/disable 方法, 可以实现你的效果
