### ISSUE TITLE
多文件上传formdata post的时候大于一定大小上传被pending？

### ISSUE THREAD

**Issue by nuintun** [aralejs/upload#24]
![qq20131231150832](https://f.cloud.github.com/assets/1730277/1826130/b4a0ff6e-71ea-11e3-9975-0abbf75491d8.png)
直接上图，选了两张图片！服务器上传大小设定在了1G！

**Comment by lizzie** [comment]
大于一定大小是多少, 是前端还是服务器的限制?

**Comment by nuintun** [comment]
@lizzie 前后台都没做限定！
