### ISSUE TITLE
jquery版本会影响uploadjs

### ISSUE THREAD

**Issue by kernnel** [aralejs/upload#30]
我的环境
seajs 1.3.1
jquery 1.10.2
upload.js

我把下载的demo放到apache下面运行的，相应的路径我已经改过来了，运行的时候提示
![image](https://cloud.githubusercontent.com/assets/1452833/2704849/f4cb6002-c474-11e3-8c54-3ef2230052b1.png)
，但是我把jquery换成1.7版本，就没有这个错误了

**Comment by billwing** [comment]
发现在`jquery-1.3.2`下面，图片没有传过去，而且`Content-Type:false`
这是Ajax的问题么，请教 @lifesinger @afc163  @lepture

**Comment by afc163** [comment]
@billwing 1.3.2 就算了，实在太老了，请使用 1.7.2 及以上版本。

**Comment by afc163** [comment]
@kernnel 哪个语句报错？upload的版本号是多少？用得是 dist 里的文件还是源码？你给的信息远远远远远远远远远远不够啊。。。

**Comment by billwing** [comment]
@afc163 THX，明白。
一个又老又大的项目，改动jquery影响较大，我再看看有没有更好的解决方案~
