### ISSUE TITLE
跨域 iframe 上传时报错的问题

### ISSUE THREAD

**Issue by afc163** [aralejs/upload#37]
https://github.com/blueimp/jQuery-File-Upload/commit/d5bc1e830f97406d336bf886662f10018d9d723a

**Comment by lepture** [comment]
本来就不应该出现跨域呀

**Comment by afc163** [comment]
页面修改了 domain ， 比如 `example.com`，iframe 上传时 form 的 action 是 `www.example.com/upload/` 这样时就会出现跨域。因为默认生成的 iframe 的 domain 就是 `www.example.com`。
