### ISSUE TITLE
IE8：上传到七牛的问题

### ISSUE THREAD

**Issue by radision** [aralejs/upload#46]
coffeescript代码如下：

```
   @uploader = new Uploader
      name: 'file'
      size: 2048000
      trigger: @$("#btn-upload")
      action: "http://upload.qiniu.com"
      data: {token: @upload_token}
      accept: 'image/*'
      multiple: false
  .success (data) =>
      console.log data
```

ff，chrome，IE9+都没问题，在IE8中，上传文件后，出现下载文件提示，下载的文件内容就是七牛返回的内容

在demo.html中尝试 action: '/' 正常，action: '//upload.qiniu.com' 提示下载文件

**Comment by radision** [comment]
![screen_ie8](https://cloud.githubusercontent.com/assets/1814341/6038096/21d0a7a2-ac95-11e4-9acf-216947f2d6c3.png)

**Comment by ICELI** [comment]
ie下要修改返回的文档类型

**Comment by billwing** [comment]
@ICELI 请问怎么修改呢，踩坑中。。

**Comment by billwing** [comment]
找到解决办法了 http://kb.qiniu.com/5487y5np
